site_name: KFR
theme:
  name: 'material'
  features:
    - navigation.tabs
    - navigation.top
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
extra:
  search:
    language: en

  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/kfrlib'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/kfrlib'

copyright: 'Copyright &copy; 2016 - 2023 KFR'

plugins:
    - search

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - js/math.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css
  - css/fix.css

repo_url: https://github.com/kfrlib/kfr
repo_name: KFR
edit_uri: edit/master/docs/

nav:
  - KFR:
    - index.md
    - whatsnew5.md
    - installation.md
    - basics.md
    - expressions.md
    - capi.md
    - upgrade5.md
  - DSP:
    - fir.md
    - bq.md
    - src.md
    - conv_reverb.md
    - ebur128.md
    - conversion.md
    - normalize.md
    - convert_stereo.md
    - fir_gallery.md
    - iir_gallery.md
    - bq_gallery.md
    - src_gallery.md
    - window_gallery.md
    - convolution.md
  - DFT:
    - dft.md
    - dft2.md
    - dft_format.md
  - I/O:
    - read_audio.md
    - file_support.md
    - plot.md
  - Reference:
    - auto/refindex.md
    - Math:
      - auto/complex.md
      - auto/constants.md
      - auto/logical.md
      - auto/basic_math.md
      - auto/exponential.md
      - auto/round.md
      - auto/saturation.md
      - auto/trigonometric.md
      - auto/hyperbolic.md
      - auto/horizontal.md
      - auto/other_math.md
    - Base:
      - auto/types.md
      - auto/univector.md
      - auto/tensor.md
      - auto/expressions.md
      - auto/generators.md
      - auto/reducing.md
      - auto/random.md
      - auto/memory.md
      - auto/conversion.md
      - auto/sort.md
      - auto/utility.md
    - DSP:
      - auto/filter.md
      - auto/biquad.md
      - auto/fir.md
      - auto/window.md
      - auto/dsp.md
      - auto/dsp_extra.md
    - DFT:
      - auto/convolution.md
      - auto/dft.md
    - IO:
      - auto/binary_io.md
      - auto/audio_io.md
      - auto/plotting.md
      - auto/string_io.md
    - Other functions: auto/default.md
    - auto/cpuid.md
    - auto/cometa.md

  - kfr.dev: https://kfr.dev
